"""Create user table

Revision ID: 42ff97af778b
Revises: None
Create Date: 2015-03-14 12:50:07.726000

"""

# revision identifiers, used by Alembic.
revision = '42ff97af778b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    op.create_table(
        'account',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('name', sa.String(50), nullable=False),
        sa.Column('description', sa.Unicode(200)),
    )


def downgrade():
    # commands auto generated by Alembic - please adjust!
    op.drop_table('account')
    # end Alembic commands
